### ISSUE TITLE
Some references need updates

### ISSUE THREAD

**Issue by ana-cc** [ana-cc/Extension-Headers#11]
- [x] I am not sure that SRv6 is defined (page 2)
- [x] Reference [36] is a little bit old (2016) for a reference that presents the IPv6 adoption today
- [x] Do the authors have a reference about the fact that routers have a parsing buffer of 104Bytes (page 5).

**Comment by gorryfair** [comment]
Be sure to say that  this is the info not just the MAC header

**Comment by ana-cc** [comment]
I've added:

This is consistent with available router parsing buffers of 128B, of which several bytes are reserved for parsing packet Layer 2 header information~\cite{apnic-buffers}~\cite{ietf-6man-eh-limits-04}.

**Comment by gorryfair** [comment]
/available router parsing buffers/  is it better as /a router parsing buffer/
