### ISSUE TITLE
Racing part

### ISSUE THREAD

**Issue by gorryfair** [ana-cc/Extension-Headers#14]
Moving this here: There is an inherent challenge with racing that you are probably aware of, which is that it poorly scales when the number of orthogonal features increases. Today, racing is used to decide between IPv4 and IPv6 in Happy Eyeballs, and some foresee using it to race QUIC and TCP. All together, this leads to four states. When adding one EH, it adds two more. I feel this issue is out of scope, and I don't have any recommendations or changes I would like to request on the text. But while I agree that we need to better optionally utilize these EHs for them to become a reality (a bit like RFC 8701), I think there are more thoughts to have on the way it could happen and more interesting work in that direction.

**Comment by gorryfair** [comment]
This is true, but we should perhaps expand on what we say - since we are not talking about "connection steup" reacing, in which there are scaling limitations. The racing here could be after connection establishment, which would reduce the interaction with other racing to setup the connection. That needed to be clearer, for the reasons the reviewer noted.

**Comment by ana-cc** [comment]
Addde the text where we first introduce this idea:

An application can be designed to first send a test packet including an EH with the required Option, or combination of Options, and not send additional packets that include this Option until the test packet is acknowledged. The process of sending packets both with and without a header to discover whether a path can support that specific header is sometimes called "racing" (e.g., transport protocol racing is explained in~\cite{ietf-taps-arch-18}; this resembles "A/B protocol feature testing", as used in Pathspider~\cite{learmonth2016pathspider}). **Racing this feature could be implemented after connection establishment, to reduce the interaction with other racing to setup the connection.**

**Comment by gorryfair** [comment]
/to setup/that setup/

Gorry
